# Generated by Django 4.2.7 on 2024-01-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='salaire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
