# Generated by Django 4.2.7 on 2024-01-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_time', '0004_alter_customuser_role_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='employee', max_length=50, unique=True),
        ),
    ]
